### ISSUE TITLE
Too much CPU usage

### ISSUE THREAD

**Issue by ligq** [xupefei/QuickLook#73] opened 2017-08-16 15:00 UTC
On my computer, the CPU usage of quicklook keeps around 10%, even for a simple text preiview.

**Comment by weiyideai520** [comment] 2017-08-17 08:03
我的也是，好卡。不知道有啥办法能解决

**Comment by fan-cy** [comment] 2017-08-19 08:03
the GPU usage is even worse

**Comment by klzsysy** [comment] 2017-08-19 09:18
内存使用突破500M... 太多了吧

**Comment by xupefei** [comment] 2017-08-19 09:33
I think the CPU usage is related to the background timer for monitoring selection change. I will fix it soon.

Regarding the GPU useage, it is normal since WPF is hardware-accelerated. 

For the Memory usage, CLR garbage collector will free memory when your system is under pressure. If you believe it is a memory leak, please tell me how to reproduce it.

**Comment by EMLVIRUS** [comment] 2017-08-19 23:32
同求 STR
![image](https://user-images.githubusercontent.com/16912240/29490795-aba919ae-8579-11e7-879c-0379183b6ae7.png)

**Comment by xupefei** [comment] 2017-11-05 21:57
我无法复现这个问题，即使在我的 Surface Pro 4 m3-6Y30 锁最低频率（0.9 GHz）的情况下，打开文本预览后的 CPU 占用率是 3% 左右，关闭预览窗口后占用率归零。我是在最新版里测试的，可能和以前的版本表现不同。
我先把这个挪到 Future 里去。

**Comment by ligq** [comment] 2017-11-06 02:23
I tried the latest version, the CPU usage drops to about 2% on my computer. Thank you. But I think CPU usage could be optimized further. Quicklook dose not have to monitor the change. For Seer to preview a simple text file,  the CPU usage is about 2% just after I press the space button, then it will soon drop to almost 0%. However the Quicklook will hold the CPU usage till I escape the preview. 

In the past two weeks you made a lot of updates. Seems sometimes you worked overnights. Thank you for your great effort to develop such a nice tool. I hope you can give us a chance to make a donation.

**Comment by xupefei** [comment] 2017-11-06 07:32
I am in the UTC+2 timezone so it is not quite "overnight" for me (except for last Thursday, I think).

I do not accept donations because (i) I am satisfied with current salary I got, (ii) I am lazy to deal with issues related to donation, (iii) QL references lots of [excellent third-party libs](https://github.com/xupefei/QuickLook/wiki/On-the-Shoulders-of-Giants) and _they_ are not asking for donations - so why should I do? Finally, (iv) in my opinion, reporting issues (or contributing codes) is the best way to show appreciation.

**Comment by xupefei** [comment] 2018-02-03 16:32
The underlying issue has been fixed in a63fd77a50d5623961202988e0369d3ec9510ece. Should you download the Nightly version, you may see the improvements.

**Closed by xupefei** 2018-02-03 16:32 UTC
Labels: bug
