### ISSUE TITLE
Ability to adjust video playback speed while previewing a video

### ISSUE THREAD

**Issue by Shae-Clark** [xupefei/QuickLook#1411] opened 2024-03-30 22:08 UTC
**Is your feature request related to a problem? Please describe.**
Not necessarily a "problem" but more of an annoyance & a way to improve the app. When needing to preview longer videos, I like to be able to get through them faster by changing the playback speed to 1.2 or 1.5. Having the ability to do that in the app would be AMAZING!

**Describe the solution you'd like**
The ability to change the playback speed

**Comment by rabelux** [comment] 2024-04-01 20:12
Duplicate of #855

**Closed as completed by rabelux** 2024-04-01 20:12 UTC
Labels: duplicate
